// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQo0Gqq3UKghUT8QAwnF6spMikSYU2GRg',
    appId: '1:16078023373:web:1017ffe3e78f990c009784',
    messagingSenderId: '16078023373',
    projectId: 'sign-up1-e8164',
    authDomain: 'sign-up1-e8164.firebaseapp.com',
    storageBucket: 'sign-up1-e8164.firebasestorage.app',
    measurementId: 'G-X8CRN8NZCQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJQTFE_oUyE7NlgI3uNhFIaR7uR4_sxO8',
    appId: '1:16078023373:android:66bccfb095e4d894009784',
    messagingSenderId: '16078023373',
    projectId: 'sign-up1-e8164',
    storageBucket: 'sign-up1-e8164.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQo0Gqq3UKghUT8QAwnF6spMikSYU2GRg',
    appId: '1:16078023373:web:81943d4791519b89009784',
    messagingSenderId: '16078023373',
    projectId: 'sign-up1-e8164',
    authDomain: 'sign-up1-e8164.firebaseapp.com',
    storageBucket: 'sign-up1-e8164.firebasestorage.app',
    measurementId: 'G-ZRDQ31X6E9',
  );
}
